<?php

namespace luckyBundle\Repository;

/**
 * Band
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Band extends \Doctrine\ORM\EntityRepository
{
}
