<?php

namespace luckyBundle\Repository;

/**
 * Concert
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Concert extends \Doctrine\ORM\EntityRepository
{
}
