<?php

namespace luckyBundle\Repository;

/**
 * Mailing
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mailing extends \Doctrine\ORM\EntityRepository
{
}
