<?php

namespace luckyBundle\Repository;

/**
 * Song
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Song extends \Doctrine\ORM\EntityRepository
{
}
