<?php

namespace luckyBundle\Repository;

/**
 * Video
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Video extends \Doctrine\ORM\EntityRepository
{
}
